"""little fix

Revision ID: cc3334570477
Revises: c9fb31da4f0b
Create Date: 2026-05-12 17:08:57.894635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc3334570477"
down_revision: Union[str, Sequence[str], None] = "c9fb31da4f0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_members",
        sa.Column("display_name", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_members", "display_name")
    # ### end Alembic commands ###
