"""add post_reaction

Revision ID: 875f714fa807
Revises: b06a917a164d
Create Date: 2026-05-11 17:43:48.359515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "875f714fa807"
down_revision: Union[str, Sequence[str], None] = "b06a917a164d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("reaction_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_post_reactions_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_reactions_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_reactions")),
        sa.UniqueConstraint(
            "post_id", "member_id", name="unique_post_member_reaction"
        ),
    )
    op.create_index(
        op.f("ix_post_reactions_member_id"),
        "post_reactions",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_post_reactions_post_id"),
        "post_reactions",
        ["post_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_post_reactions_post_id"), table_name="post_reactions"
    )
    op.drop_index(
        op.f("ix_post_reactions_member_id"), table_name="post_reactions"
    )
    op.drop_table("post_reactions")
    # ### end Alembic commands ###
