"""add family_group_id to posts

Revision ID: 8b0f62830456
Revises: a947b1ed072b
Create Date: 2026-05-19 22:24:46.997231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8b0f62830456"
down_revision: Union[str, Sequence[str], None] = "a947b1ed072b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("family_group_id", sa.UUID(), nullable=True))

    op.execute("""
               UPDATE posts
               SET family_group_id = (
                   SELECT family_group_id
                   FROM family_members
                   WHERE family_members.linked_user_id = posts.author_id
                   LIMIT 1
               )
               WHERE family_group_id IS NULL
               """)
    op.alter_column("posts", "family_group_id", nullable=False)

    op.create_index(
        op.f("ix_posts_family_group_id"),
        "posts",
        ["family_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_posts_family_group_id_family_groups"),
        "posts",
        "family_groups",
        ["family_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_posts_family_group_id_family_groups"),
        "posts",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_posts_family_group_id"), table_name="posts")
    op.drop_column("posts", "family_group_id")
    # ### end Alembic commands ###
