"""little fix

Revision ID: b77ecd243746
Revises: 837cf0206f1b
Create Date: 2026-05-11 17:59:18.059114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b77ecd243746"
down_revision: Union[str, Sequence[str], None] = "837cf0206f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_posts_belongs_to_member_id"), table_name="posts")
    op.create_index(
        op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False
    )
    op.drop_constraint(
        op.f("posts_belongs_to_member_id_fkey"), "posts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_posts_user_id_users"), "posts", "users", ["user_id"], ["id"]
    )
    op.drop_column("posts", "belongs_to_member_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "belongs_to_member_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_posts_user_id_users"), "posts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("posts_belongs_to_member_id_fkey"),
        "posts",
        "family_members",
        ["belongs_to_member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.create_index(
        op.f("ix_posts_belongs_to_member_id"),
        "posts",
        ["belongs_to_member_id"],
        unique=False,
    )
    op.drop_column("posts", "user_id")
    # ### end Alembic commands ###
