"""Added relationships

Revision ID: 1591854004c7
Revises: 0255d7a9e77b
Create Date: 2026-04-23 18:40:00.714558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1591854004c7"
down_revision: Union[str, Sequence[str], None] = "0255d7a9e77b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    membership_role = sa.Enum("admin", "editor", "viewer", name="membershiprole")
    membership_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "editor", "viewer", name="membershiprole"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum(name="membershiprole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
