"""delete  role to fam member

Revision ID: a947b1ed072b
Revises: cc3334570477
Create Date: 2026-05-18 17:11:57.994584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a947b1ed072b"
down_revision: Union[str, Sequence[str], None] = "cc3334570477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_members", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_members",
        sa.Column(
            "role",
            postgresql.ENUM(
                "admin", "editor", "viewer", name="membership_role_enum"
            ),
            server_default=sa.text("'editor'::membership_role_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
