"""add is_favourite to FamilyMembership model

Revision ID: b06a917a164d
Revises: 1591854004c7
Create Date: 2026-05-09 18:53:28.904631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b06a917a164d"
down_revision: Union[str, Sequence[str], None] = "1591854004c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_memberships",
        sa.Column(
            "is_favourite",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_memberships", "is_favourite")
    # ### end Alembic commands ###
