"""little fix

Revision ID: 837cf0206f1b
Revises: 875f714fa807
Create Date: 2026-05-11 17:57:02.653089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "837cf0206f1b"
down_revision: Union[str, Sequence[str], None] = "875f714fa807"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_files", sa.Column("user_id", sa.UUID(), nullable=False)
    )
    op.drop_index(
        op.f("ix_media_files_family_group_id"), table_name="media_files"
    )
    op.drop_constraint(
        op.f("media_files_family_group_id_fkey"),
        "media_files",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("media_files_uploaded_by_fkey"), "media_files", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_media_files_user_id_users"),
        "media_files",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("media_files", "uploaded_by")
    op.drop_column("media_files", "family_group_id")
    op.drop_index(op.f("ix_posts_family_group_id"), table_name="posts")
    op.drop_constraint(
        op.f("posts_family_group_id_fkey"), "posts", type_="foreignkey"
    )
    op.drop_column("posts", "event_date")
    op.drop_column("posts", "family_group_id")
    op.drop_column("posts", "event_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "event_description",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "family_group_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "posts",
        sa.Column("event_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("posts_family_group_id_fkey"),
        "posts",
        "family_groups",
        ["family_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_posts_family_group_id"),
        "posts",
        ["family_group_id"],
        unique=False,
    )
    op.add_column(
        "media_files",
        sa.Column(
            "family_group_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "media_files",
        sa.Column(
            "uploaded_by", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_media_files_user_id_users"), "media_files", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("media_files_uploaded_by_fkey"),
        "media_files",
        "users",
        ["uploaded_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("media_files_family_group_id_fkey"),
        "media_files",
        "family_groups",
        ["family_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_media_files_family_group_id"),
        "media_files",
        ["family_group_id"],
        unique=False,
    )
    op.drop_column("media_files", "user_id")
    # ### end Alembic commands ###
