"""Initial migration

Revision ID: 0255d7a9e77b
Revises:
Create Date: 2026-04-21 22:50:55.623513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0255d7a9e77b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_family_members_group"), table_name="family_members"
    )
    op.drop_index(
        op.f("idx_family_members_linked_user"), table_name="family_members"
    )
    op.drop_index(op.f("idx_members_group"), table_name="family_members")
    op.create_index(
        op.f("ix_family_members_family_group_id"),
        "family_members",
        ["family_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_members_linked_user_id"),
        "family_members",
        ["linked_user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("family_memberships_user_id_family_group_id_key"),
        "family_memberships",
        type_="unique",
    )
    op.drop_index(
        op.f("idx_memberships_group"), table_name="family_memberships"
    )
    op.drop_index(
        op.f("idx_memberships_user"), table_name="family_memberships"
    )
    op.create_unique_constraint(
        op.f("uq_family_memberships_user_id_family_group_id"),
        "family_memberships",
        ["user_id", "family_group_id"],
    )
    op.drop_index(op.f("idx_invitations_token"), table_name="invitations")
    op.drop_constraint(
        op.f("invitations_token_key"), "invitations", type_="unique"
    )
    op.create_index(
        op.f("ix_invitations_token"), "invitations", ["token"], unique=True
    )
    op.drop_index(op.f("idx_media_group"), table_name="media_files")
    op.drop_index(op.f("idx_media_post"), table_name="media_files")
    op.create_index(
        op.f("ix_media_files_family_group_id"),
        "media_files",
        ["family_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_files_post_id"),
        "media_files",
        ["post_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_posts_attributed_to"), table_name="posts")
    op.drop_index(op.f("idx_posts_author"), table_name="posts")
    op.drop_index(op.f("idx_posts_belongs_to"), table_name="posts")
    op.drop_index(op.f("idx_posts_created"), table_name="posts")
    op.drop_index(op.f("idx_posts_group"), table_name="posts")
    op.create_index(
        op.f("ix_posts_attributed_to_member_id"),
        "posts",
        ["attributed_to_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_posts_author_user_id"),
        "posts",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_posts_belongs_to_member_id"),
        "posts",
        ["belongs_to_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_posts_family_group_id"),
        "posts",
        ["family_group_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_relationships_from"), table_name="relationships")
    op.drop_index(op.f("idx_relationships_group"), table_name="relationships")
    op.drop_index(op.f("idx_relationships_to"), table_name="relationships")
    op.drop_constraint(
        op.f(
            "relationships_family_group_id_from_member_id_to_member_id_r_key"
        ),
        "relationships",
        type_="unique",
    )
    op.create_index(
        op.f("ix_relationships_family_group_id"),
        "relationships",
        ["family_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_from_member_id"),
        "relationships",
        ["from_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_to_member_id"),
        "relationships",
        ["to_member_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_relationships_group_members_type",
        "relationships",
        ["family_group_id", "from_member_id", "to_member_id", "rel_type"],
    )
    op.drop_index(op.f("idx_tags_group"), table_name="tags")
    op.drop_constraint(
        op.f("tags_family_group_id_name_key"), "tags", type_="unique"
    )
    op.create_index(
        op.f("ix_tags_family_group_id"),
        "tags",
        ["family_group_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_tags_family_group_id_name"),
        "tags",
        ["family_group_id", "name"],
    )
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.drop_constraint(
        op.f("uq_tags_family_group_id_name"), "tags", type_="unique"
    )
    op.drop_index(op.f("ix_tags_family_group_id"), table_name="tags")
    op.create_unique_constraint(
        op.f("tags_family_group_id_name_key"),
        "tags",
        ["family_group_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_tags_group"), "tags", ["family_group_id"], unique=False
    )
    op.drop_constraint(
        "uq_relationships_group_members_type", "relationships", type_="unique"
    )
    op.drop_index(
        op.f("ix_relationships_to_member_id"), table_name="relationships"
    )
    op.drop_index(
        op.f("ix_relationships_from_member_id"), table_name="relationships"
    )
    op.drop_index(
        op.f("ix_relationships_family_group_id"), table_name="relationships"
    )
    op.create_unique_constraint(
        op.f(
            "relationships_family_group_id_from_member_id_to_member_id_r_key"
        ),
        "relationships",
        ["family_group_id", "from_member_id", "to_member_id", "rel_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_relationships_to"),
        "relationships",
        ["to_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_relationships_group"),
        "relationships",
        ["family_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_relationships_from"),
        "relationships",
        ["from_member_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_posts_family_group_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.drop_index(op.f("ix_posts_belongs_to_member_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_author_user_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_attributed_to_member_id"), table_name="posts")
    op.create_index(
        op.f("idx_posts_group"), "posts", ["family_group_id"], unique=False
    )
    op.create_index(
        op.f("idx_posts_created"),
        "posts",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_posts_belongs_to"),
        "posts",
        ["belongs_to_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_posts_author"), "posts", ["author_user_id"], unique=False
    )
    op.create_index(
        op.f("idx_posts_attributed_to"),
        "posts",
        ["attributed_to_member_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_media_files_post_id"), table_name="media_files")
    op.drop_index(
        op.f("ix_media_files_family_group_id"), table_name="media_files"
    )
    op.create_index(
        op.f("idx_media_post"), "media_files", ["post_id"], unique=False
    )
    op.create_index(
        op.f("idx_media_group"),
        "media_files",
        ["family_group_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.create_unique_constraint(
        op.f("invitations_token_key"),
        "invitations",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_invitations_token"), "invitations", ["token"], unique=True
    )
    op.drop_constraint(
        op.f("uq_family_memberships_user_id_family_group_id"),
        "family_memberships",
        type_="unique",
    )
    op.create_index(
        op.f("idx_memberships_user"),
        "family_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_memberships_group"),
        "family_memberships",
        ["family_group_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("family_memberships_user_id_family_group_id_key"),
        "family_memberships",
        ["user_id", "family_group_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_family_members_linked_user_id"), table_name="family_members"
    )
    op.drop_index(
        op.f("ix_family_members_family_group_id"), table_name="family_members"
    )
    op.create_index(
        op.f("idx_members_group"),
        "family_members",
        ["family_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_family_members_linked_user"),
        "family_members",
        ["linked_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_family_members_group"),
        "family_members",
        ["family_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###
