"""little fix

Revision ID: c9fb31da4f0b
Revises: 296146530010
Create Date: 2026-05-12 14:06:53.033821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9fb31da4f0b"
down_revision: Union[str, Sequence[str], None] = "296146530010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE membership_role_enum AS ENUM ('admin', 'editor', 'viewer')")
    op.add_column(
        "family_members",
        sa.Column(
            "role",
            postgresql.ENUM(
                "admin",
                "editor",
                "viewer",
                name="membership_role_enum",
                inherit_schema=True,
            ),
            server_default="editor",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_members", "role")
    # ### end Alembic commands ###
