"""little fix

Revision ID: 296146530010
Revises: b77ecd243746
Create Date: 2026-05-12 13:14:17.033338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "296146530010"
down_revision: Union[str, Sequence[str], None] = "b77ecd243746"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("author_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_posts_author_user_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.create_index(
        op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_posts_user_id_users"), "posts", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("posts_author_user_id_fkey"), "posts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_posts_author_id_users"),
        "posts",
        "users",
        ["author_id"],
        ["id"],
    )
    op.drop_column("posts", "user_id")
    op.drop_column("posts", "author_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "author_user_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "posts",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_posts_author_id_users"), "posts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("posts_author_user_id_fkey"),
        "posts",
        "users",
        ["author_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_posts_user_id_users"), "posts", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.create_index(
        op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_posts_author_user_id"),
        "posts",
        ["author_user_id"],
        unique=False,
    )
    op.drop_column("posts", "author_id")
    # ### end Alembic commands ###
